### ISSUE TITLE
Can't use AutoStructify

### ISSUE THREAD

**Issue by ericoporto** [ericoporto/agshelp#1]
Ideally one could use Markdown with Sphinx and get doctree benefits.
To be fully able of doing this, some code has to be added on `conf.py`

    import recommonmark
    from recommonmark.transform import AutoStructify

and at the end of `conf.py`

    # -- Extension configuration -------------------------------------------------
    def setup(app):
        app.add_config_value('recommonmark_config', {
                'url_resolver': lambda url: 'https://github.com/ericoporto/agshelp/wiki/' + url,
                'auto_toc_tree_section': 'Contents',
                }, True)
        app.add_transform(AutoStructify)

But by doing this it triggers a crash on File.md line 356 apparently.

    $ make html
    Running Sphinx v1.7.5
    loading pickled environment... not yet created
    building [mo]: targets for 0 po files that are out of date
    building [html]: targets for 110 source files that are out of date
    updating environment: 110 added, 0 changed, 0 removed
    /usr/local/lib/python3.5/dist-packages/recommonmark/parser.py:280: UserWarning: Unsupported inline type Hardbreak    
      warn("Unsupported inline type " + inline.t)
    reading sources... [ 29%] agshelp.wiki/File                                                                          
    Exception occurred:
      File "/usr/local/lib/python3.5/dist-packages/docutils/parsers/rst/roles.py", line 356, in math_role
        text = rawtext.split('`')[1]
    IndexError: list index out of range
    The full traceback has been saved in /tmp/sphinx-err-kbdzncf9.log, if you want to report the issue to the developers.
    Please also report this if it was a user error, so that a better error message can be provided next time.
    A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
    Makefile:20: recipe for target 'html' failed
    make: *** [html] Error 2

This triggers the log as

    # Sphinx version: 1.7.5
    # Python version: 3.5.2 (CPython)
    # Docutils version: 0.14 
    # Jinja2 version: 2.8
    # Last messages:
    #   reading sources... [ 25%] agshelp.wiki/EditingGUIs
    #   
    #   reading sources... [ 26%] agshelp.wiki/EventTypes
    #   
    #   reading sources... [ 27%] agshelp.wiki/ExtenderFunctions
    #   
    #   reading sources... [ 28%] agshelp.wiki/FAQ
    #   
    #   reading sources... [ 29%] agshelp.wiki/File
    #   
    # Loaded extensions:
    #   alabaster (0.7.11) from /usr/local/lib/python3.5/dist-packages/alabaster/__init__.py
    #   sphinx.ext.githubpages (1.7.5) from /usr/local/lib/python3.5/dist-packages/sphinx/ext/githubpages.py
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/sphinx/cmdline.py", line 304, in main
        app.build(args.force_all, filenames)
      File "/usr/local/lib/python3.5/dist-packages/sphinx/application.py", line 331, in build
        self.builder.build_update()
      File "/usr/local/lib/python3.5/dist-packages/sphinx/builders/__init__.py", line 342, in build_update
        'out of date' % len(to_build))
      File "/usr/local/lib/python3.5/dist-packages/sphinx/builders/__init__.py", line 355, in build
        updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
      File "/usr/local/lib/python3.5/dist-packages/sphinx/environment/__init__.py", line 565, in update
        self._read_serial(docnames, self.app)
      File "/usr/local/lib/python3.5/dist-packages/sphinx/environment/__init__.py", line 584, in _read_serial
        self.read_doc(docname, app)
      File "/usr/local/lib/python3.5/dist-packages/sphinx/environment/__init__.py", line 659, in read_doc
        doctree = read_doc(self.app, self, self.doc2path(docname))
      File "/usr/local/lib/python3.5/dist-packages/sphinx/io.py", line 294, in read_doc
        pub.publish()
      File "/usr/local/lib/python3.5/dist-packages/docutils/core.py", line 218, in publish
        self.apply_transforms()
      File "/usr/local/lib/python3.5/dist-packages/docutils/core.py", line 199, in apply_transforms
        self.document.transformer.apply_transforms()
      File "/usr/local/lib/python3.5/dist-packages/sphinx/transforms/__init__.py", line 96, in apply_transforms
        Transformer.apply_transforms(self)
      File "/usr/local/lib/python3.5/dist-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
        transform.apply(**kwargs)
      File "/usr/local/lib/python3.5/dist-packages/recommonmark/transform.py", line 325, in apply
        self.traverse(self.document)
      File "/usr/local/lib/python3.5/dist-packages/recommonmark/transform.py", line 297, in traverse
        self.traverse(child)
      File "/usr/local/lib/python3.5/dist-packages/recommonmark/transform.py", line 297, in traverse
        self.traverse(child)
      File "/usr/local/lib/python3.5/dist-packages/recommonmark/transform.py", line 297, in traverse
        self.traverse(child)
      File "/usr/local/lib/python3.5/dist-packages/recommonmark/transform.py", line 287, in traverse
        newnode = self.find_replace(c)
      File "/usr/local/lib/python3.5/dist-packages/recommonmark/transform.py", line 271, in find_replace
        newnode = self.auto_inline_code(node)
      File "/usr/local/lib/python3.5/dist-packages/recommonmark/transform.py", line 207, in auto_inline_code
        return self.state_machine.run_role('math', content=content)
      File "/usr/local/lib/python3.5/dist-packages/recommonmark/states.py", line 134, in run_role
        content=content)
      File "/usr/local/lib/python3.5/dist-packages/docutils/parsers/rst/roles.py", line 356, in math_role
        text = rawtext.split('`')[1]
    IndexError: list index out of range

I can't for now figure out what is wrong with `File.md`

**Comment by tzachshabtay** [comment]
It's not in line 356 of File.md but line 356 of roles.py (this line: https://github.com/docutils-mirror/docutils/blob/e88c5fb08d5cdfa8b4ac1020dd6f7177778d5990/docutils/parsers/rst/roles.py#L355).
It expects a \` in the rawtext it gets as input, but there is none there.
If you follow the stacktrace a little up, you see that the "math" role is called in this line: https://github.com/rtfd/recommonmark/blob/956bf18b24d48ff0b496d7464bc01a368fb97807/recommonmark/transform.py#L211
That line is inside an `if content.startswith('$') and content.endswith('$')`. A section inside 2 dollar signs can be interpreted as a math formula in a markdown document (see here: https://meta.stackexchange.com/questions/263343/is-the-dollar-sign-used-for-markdown-if-yes-then-how-can-i-safely-insert-i), so I guess that's the problem, though I don't know where File.md actually sits so can't verify, I don't see it in this repo?

**Comment by morganwillcock** [comment]
It looks like it is probably the path tokens in that file:
<pre>grep --only-matching "\$.*\$" File.md

$INSTALLDIR$`, which allows you to explicitly read files in the game
$SAVEGAMEDIR$`, which allows you to write/read files in the save game
$APPDATADIR$`, which allows you to write/read files to a folder on the
$SAVEGAMEDIR$` or
$APPDATADIR$` locations. An attempt to write file in `$INSTALLDIR$`
$APPDATADIR$`. This is done for
$SAVEGAMEDIR$/temp.tmp", eFileWrite);
$SAVEGAMEDIR$` and `$APPDATADIR$` directories.
$APPDATADIR$/temp.tmp");
$INSTALLDIR$`, which allows you to explicitly read files in the game
$SAVEGAMEDIR$`, which allows you to access files in the save game
$APPDATADIR$`, which allows you to write/read files to a folder on the</pre>

@tzachshabtay you can checkout the wiki pages using the URL:
[https://github.com/ericoporto/agshelp.wiki.git](https://github.com/ericoporto/agshelp.wiki.git)

**Comment by morganwillcock** [comment]
It will build if you add `'enable_inline_math': False` to the extension config.

**Comment by ericoporto** [comment]
@morganwillcock you are right, it worked!

**Comment by ericoporto** [comment]
@morganwillcock you are right! it worked!

@tzachshabtay the wiki can be accessed directly here: https://github.com/ericoporto/agshelp/wiki

Since I can use AutoStructify I am closing this issue.
